// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace VennDiagram
{
	public partial class Venn : UIView
	{
		public Venn (IntPtr handle) : base (handle)
		{
		}
	}
}
